project:
  type: website
  output-dir: docs

website:
  title: "Statistics 515 Lab #2 Demo Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Favorites.qmd
      - Organization Involvement.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

