---
title: "Organization Involvement Outside of School"
---

Volunteer Positions:

-   Sigma Psi Zeta Sorority, Inc. Regional Director (July 2023 - Present)

-   Mid-Atlantic Union of Vietnamese Student Associations Advisor (July 2022 - June 2023)

-   Mid-Atlantic Union of Vietnamese Student Associations Food Committee Member (May 2022 - July 2022)

-   Union of North American Vietnamese Student Associations Programming Committee Member (November 2021 - July 2022)

-   Mid-Atlantic Union of Vietnamese Student Associations Secretary (May 2021 - July 2022)

-   Mid-Atlantic Union of Vietnamese Student Associations MAC X Executive Team (September 2021 - February 2022)

-   Mid-Atlantic Union of Vietnamese Student Associations MAC IX/X Sponsorship Chairperson (September 2020 - February 2022)

-   Mid-Atlantic Union of Vietnamese Student Associations MLC 8 Logistics Chairperson (June 2021 - August 2021)

-   Mid-Atlantic Union of Vietnamese Student Associations Alumni Association Chairperson (September 2020 - May 2021)

-   Sigma Psi Zeta Sorority, Inc. Alpha Nu Chapter Secretary (May 2019 - May 2020)

-   Sigma Psi Zeta Sorority, Inc. Alpha Nu Chapter Fundraising Chairperson (November 2018 - May 2019)

-   Sigma Psi Zeta Sorority, Inc. Alpha Nu Chapter Treasurer (November 2017 - May 2019)
